language: c

sudo: false

before_install:
  - export DEVKITPRO=${HOME}/devkitPro
  - export DEVKITARM=${DEVKITPRO}/devkitARM
  - export CTRULIB=${DEVKITPRO}/libctru
  - sh .travis-deps.sh

script:
  - make -j4
